### ISSUE TITLE
id field should NOT be required on Add

### ISSUE THREAD

**Issue by wardbell** [johnpapa/angular-ngrx#62]
Because server can/might/often-does create it.
The in-mem does.
In any event, it's not a good idea for users to create their own ids.

**Comment by johnpapa** [comment]
the database has a `_id` field. I was using that as a unique key.

but we could assume `id` is unique if you prefer.

or we can remove `id`.

or we can keep `id` and make it not required *AND* dont allow editing.

what do you want to do?
